# --- FONT ---
font_family Fira Code
bold_font auto
italic_font auto
bold_italic_font auto

font_size 12.0

# --- CURSOR ---
cursor_shape block
shell_integration no-cursor

# --- BEHAVIOR ---
mouse_hide_wait 2.0
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh

inactive_text_alpha .8
hide_window_decorations yes
resize_debounce_time 0.1 0.25

# --- TABS ---
tab_bar_style powerline
tab_powerline_style slanted
tab_activity_symbol 
tab_title_max_length 8

# --- LOOK ---
background_blur 4
background_opacity .7

# --- STUFF ---
linux_display_server wayland

# --- KEYBINDS ---
map ctrl+c copy_to_or_interrupt
map ctrl+v paste_from_clipboard

map shift+alt+t set_tab_title
map alt+t new_tab
map alt+w close_tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2

map alt+enter new_window
map alt+r     load_config_file

# BEGIN_KITTY_THEME
include current-theme.conf

background              #1d2021
foreground              #fbf1c7

cursor                  #fb4934
cursor_text_color       #1d2021
selection_background    #fb4934
selection_foreground    #1d2021

url_color               #fe8019

active_border_color     #fb4934
inactive_border_color   #fb4934

active_tab_background   #fb4934
active_tab_foreground   #1d2021
inactive_tab_background #32302f
inactive_tab_foreground #a89984

#color2                  #fb4934
#color10                 #fe8019
